#!/bin/bash

# original file location: /usr/bin/regolith-session-init

# This script initializes Regolith Xresources and launches i3.

# File Locations - Optional User Overrides
USER_XRESOURCE="$HOME/.config/regolith/Xresources"


# File Locations - Baseline
BASELINE_XRESOURCE_FILE="$HOME/.Xresources"

# Load default Xresources
if [ -f "$BASELINE_XRESOURCE_FILE" ]; then
    xrdb -merge $BASELINE_XRESOURCE_FILE
fi

# Merge user overrides of Xresources if exists
if [ -f "$USER_XRESOURCE" ]; then
    xrdb -merge $USER_XRESOURCE
fi

# Change the quotes in workspace names from double to to single.
# Due to a limitation of the preprocessor they have double quotes.
# The i3-wm workspace command fails with double quotes in the name
xrdb -query |grep i3-wm.workspace.|sed "s/\"/'/g"|xrdb -merge

# Register with gnome-session so that it does not kill the whole session thinking it is dead.
# See https://zork.net/~st/jottings/gnome-i3.html for details
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
    dbus-send --print-reply --session --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.RegisterClient "string:Regolith" "string:$DESKTOP_AUTOSTART_ID"
fi

# Launch i3wm with the Regolith configuration
$I3_CONFIG_FILE="$HOME/.config/i3/config"
echo "Regolith is launching i3-gaps with $I3_CONFIG_FILE"
i3 -c $I3_CONFIG_FILE

# Close session when i3 exits.
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
    dbus-send --print-reply --session --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.Logout "uint32:1"
fi
