#!/usr/bin/env bash
temp=$(
    sensors 'coretemp-*' \
        | grep '^Package id' \
        | awk '{ print $4 }' \
        | grep -o '[0-9]\+' \
        | head -n1
)

ICON=""
if [[ "$temp" -lt 30 ]]; then
    ICON=""
elif [[ "$temp" -lt 40 ]]; then
    ICON=""
elif [[ "$temp" -lt 50 ]]; then
	ICON=""
elif [[ "$temp" -lt 60 ]]; then
    ICON=""
fi

echo '<span foreground="#db2c00">'$ICON'</span>' $temp°C
