#!/usr/bin/env bash
# Based on https://aur.archlinux.org/packages/playerctl/

INSTANCE="${BLOCK_INSTANCE}"

if [[ "${INSTANCE}" != "" ]]; then
  ARGUMENTS="--player ${INSTANCE}"
  ps -e | grep "${INSTANCE}" &> /dev/null
fi
if [ $? == 1 ]; then
    exit 0
fi

ICON_PLAY=""
ICON_PAUSE=" "
ICON_STOP=" "
CUR_ICON=""

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)
METADATA=$(playerctl metadata -f '{{title}} - {{artist}}')

if [[ "${PLAYER_STATUS}" = "Paused" ]]; then
  CUR_ICON="${ICON_PAUSE}"
elif [[ "${PLAYER_STATUS}" = "Playing" ]]; then
  CUR_ICON="${ICON_PLAY}"
else
  CUR_ICON="${ICON_STOP}"
fi

if [[ ${#METADATA} -gt 40 ]]; then
	METADATA="$(echo $METADATA | cut -c 1-37)..."
fi

if [[ "${METADATA}" != "" ]]; then
  echo "${CUR_ICON} ${METADATA}"
  echo "${CUR_ICON} ${METADATA}"
fi
